dynamic casting support in LaravelConfig
tarfin-labs/laravel-config pull request #31
Opened 2024-02-29 09:44 UTC by YunusEmreNalbant

Added dynamic casting support to the LaravelConfig class, enabling it to cast configuration values based on their types.

2024-03-01 06:07 UTC, tkaratug requested changes

2024-03-01 06:07 UTC, tkaratug commented on tests/LaravelConfigTest.php
> +            'type' => 'boolean',
Buraya enum case verebiliriz.

2024-03-01 06:07 UTC, tkaratug commented on tests/LaravelConfigTest.php
> +            'type' => 'integer',
Buraya enum case verebiliriz.

2024-03-01 06:07 UTC, tkaratug commented on tests/LaravelConfigTest.php
> +            'type' => 'datetime',
Buraya enum case verebiliriz.

2024-03-01 06:07 UTC, tkaratug commented on tests/LaravelConfigTest.php
> +            'type' => 'date',
Buraya enum case verebiliriz.

2024-03-01 06:07 UTC, tkaratug commented on tests/LaravelConfigTest.php
> +            'type' => 'json',
Buraya enum case verebiliriz.

2024-03-01 09:22 UTC, YunusEmreNalbant commented on tests/LaravelConfigTest.php
> +            'type' => 'boolean',
güncelledim: https://github.com/tarfin-labs/laravel-config/pull/31/commits/09968a241430042e1093144308c3131bbc9a8e33

2024-03-05 09:17 UTC, tkaratug approved these changes

2024-03-05 09:27 UTC, merged